import os
from OMPython import OMCSessionZMQ
import matplotlib.pyplot as plt

# 1. Initialize OMC Session
omc = OMCSessionZMQ()

# Check OMC version to verify connection
version = omc.sendExpression("getVersion()")
print(f"Connected to OMC Version: {version}")

# 2. Load package.mo
load_success = omc.sendExpression('loadFile("package.mo")')
print(f"Package loaded successfully: {load_success}")

if not load_success:
    print("Error: Could not load package.mo. Make sure package.mo and all component files are in this folder.")
    exit()

# 3. Simulate TwoConnectedTanks model
print("Running simulation...")
sim_result = omc.sendExpression("simulate(NonInteractingTanks.TwoConnectedTanks, stopTime=30.0)")
print("Simulation finished.")

# 4. Extract result file path generated by OMC
res_file = "NonInteractingTanks.TwoConnectedTanks_res.mat"

# Extract variable values using OMC's built-in val() expression
# val(varName, time) returns variable value at specified time point
# Alternatively, read array variables directly:
try:
    # Get simulation time vector using readSimulationResultVars / val calls
    num_points = int(omc.sendExpression(f'readSimulationResultSize("{res_file}")'))
    
    # Query time, tank1.h, and tank2.h directly from OMC session
    time = [float(omc.sendExpression(f'val(time, {t})')) for t in [i * (30.0 / 100) for i in range(101)]]
    h1 = [float(omc.sendExpression(f'val(tank1.h, {t})')) for t in [i * (30.0 / 100) for i in range(101)]]
    h2 = [float(omc.sendExpression(f'val(tank2.h, {t})')) for t in [i * (30.0 / 100) for i in range(101)]]

    # 5. Plot the simulation results
    plt.figure(figsize=(9, 5))
    plt.plot(time, h1, label="Tank 1 Height (h1)", color="blue", linewidth=2)
    plt.plot(time, h2, label="Tank 2 Height (h2)", color="orange", linewidth=2)
    
    plt.xlabel("Time (s)")
    plt.ylabel("Liquid Level (m)")
    plt.title("FOSSEE Task 2: Two Connected Tanks Simulation")
    plt.grid(True, linestyle="--", alpha=0.7)
    plt.legend()
    
    # Save the plot
    plt.savefig("simulation_results.png", dpi=300)
    print("Plot successfully saved as 'simulation_results.png'")
    plt.show()

except Exception as e:
    print(f"Error extracting simulation results: {e}")